"""Assemble the static pages: src/layout.html + src/pages/*.html -> site root.

Each page starts with a JSON comment:
  <!--{"title": "...", "desc": "...", "nav": "tests", "scripts": ["moon.js", "site.js"]}-->
An optional <!--hero--> ... <!--/hero--> block is placed inside the sky header.
Run:  python tools/build_pages.py
"""
import json
import os
import re

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(HERE, "src")
PLAY = "https://play.google.com/store/apps/details?id=com.shaadiparrot.app"


def build():
    layout = open(os.path.join(SRC, "layout.html"), encoding="utf-8").read()
    pages = sorted(f for f in os.listdir(os.path.join(SRC, "pages")) if f.endswith(".html"))
    for name in pages:
        raw = open(os.path.join(SRC, "pages", name), encoding="utf-8").read()
        m = re.match(r"\s*<!--(\{.*?\})-->\s*", raw, re.S)
        meta = json.loads(m.group(1)) if m else {}
        body = raw[m.end():] if m else raw
        # <!--include:name--> pulls in src/partials/name.html (generated by gen_catalog.py)
        body = re.sub(r"<!--include:([\w-]+)-->",
                      lambda m: open(os.path.join(SRC, "partials", m.group(1) + ".html"), encoding="utf-8").read(), body)
        hero = ""
        h = re.search(r"<!--hero-->(.*?)<!--/hero-->", body, re.S)
        if h:
            hero, body = h.group(1).strip(), body[:h.start()] + body[h.end():]
        # everything below the sky header loads lazily (budget phones on mobile data)
        body = re.sub(r"<img(?![^>]*\bloading=)", '<img loading="lazy" decoding="async"', body)
        scripts = "\n".join(f'<script src="assets/js/{s}"></script>' for s in meta.get("scripts", ["site.js"]))
        out = layout
        for key, val in {
            "title": meta.get("title", "Shaadi Parrot"),
            "desc": meta.get("desc", ""),
            "nav": meta.get("nav", ""),
            "topclass": " " + meta["topclass"] if meta.get("topclass") else "",
            "head": meta.get("head", ""),
            "hero": hero,
            "content": body.strip(),
            "scripts": scripts,
            "file": "" if name == "index.html" else name,
            "root": "",
        }.items():
            out = out.replace("{{" + key + "}}", val)
        # Play install referrer, so Play Console shows which page an install came from
        page = "home" if name == "index.html" else name[:-5].replace("-", "_")
        out = out.replace(PLAY, PLAY + f"&amp;referrer=utm_source%3Dwebsite%26utm_medium%3D{page}")
        # mark the current section in the nav
        if meta.get("nav"):
            out = out.replace(f'data-nav="{meta["nav"]}"', f'data-nav="{meta["nav"]}" aria-current="page"')
        leftover = re.findall(r"\{\{\w+\}\}", out)
        assert not leftover, (name, leftover)
        with open(os.path.join(HERE, name), "w", encoding="utf-8", newline="\n") as f:
            f.write(out)
        print("built", name)


if __name__ == "__main__":
    build()
