"""Data for the astrology pop-ups, taken from the app's own Astrology Library articles.

  assets/js/nak-data.js      27 nakshatras: hook, key facts ("At a glance"), two ideas
  assets/js/library-data.js  15 sections: all topic titles + the first topic's hook as a free preview
Run:  python tools/gen_astro_data.py
"""
import json
import os
import re

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP = os.path.join(os.path.dirname(HERE), "MauiApp2", "MauiApp2")
LIB = os.path.join(APP, "Resources", "Library")
NAKS = ["ashwini", "bharani", "krittika", "rohini", "mrigashira", "ardra", "punarvasu", "pushya", "ashlesha",
        "magha", "purva_phalguni", "uttara_phalguni", "hasta", "chitra", "swati", "vishakha", "anuradha", "jyeshtha",
        "mula", "purva_ashadha", "uttara_ashadha", "shravana", "dhanishta", "shatabhisha", "purva_bhadrapada",
        "uttara_bhadrapada", "revati"]
FACTS = ["Span", "Vimshottari lord", "Symbol", "Gana", "Rashi"]


def parse_md(path):
    text = open(path, encoding="utf-8-sig").read()
    hook = re.search(r"^hook:\s*(.+)$", text, re.M)
    ideas = re.findall(r"^idea:\s*(.+)$", text, re.M)
    glance = {}
    m = re.search(r"### At a glance\n(.*?)(?:\n###|\Z)", text, re.S)
    if m:
        for line in m.group(1).splitlines():
            line = line.strip().lstrip("•").strip()
            if ":" in line:
                k, v = line.split(":", 1)
                glance[k.strip()] = v.strip()
    return (hook.group(1).strip() if hook else ""), ideas, glance


def main():
    naks = {}
    for k in NAKS:
        hook, ideas, glance = parse_md(os.path.join(LIB, "nakshatras", k + ".md"))
        facts = [[f, glance[f]] for f in FACTS if f in glance]
        naks[k] = {"hook": hook, "facts": facts, "ideas": ideas[2:4] if len(ideas) >= 4 else ideas[:2]}
    write("nak-data.js", "NAK_DATA", naks)

    src = open(os.path.join(APP, "Services", "AstrologyLibraryContent.cs"), encoding="utf-8-sig").read()
    titles = dict(re.findall(r'"(\w+)" => "([^"]+)"', src))
    order = re.findall(r'"(\w+)"', re.search(r"SectionIds \{ get; \} =\s*\[(.*?)\];", src, re.S).group(1))
    lib = []
    for sid in order:
        block = re.search(r'\["' + sid + r'"\]\s*=\s*\[(.*?)\]\s*,?\s*(?=\["|\};)', src, re.S)
        topics = re.findall(r'\("(\w+)",\s*"([^"]+)"\)', block.group(1)) if block else []
        first_hook = ""
        if topics:
            p = os.path.join(LIB, sid, topics[0][0] + ".md")
            if os.path.exists(p):
                first_hook = parse_md(p)[0]
        lib.append({"id": sid, "title": titles.get(sid, sid), "topics": [t for _, t in topics],
                    "preview": {"title": topics[0][1] if topics else "", "hook": first_hook}})
    write("library-data.js", "LIBRARY_DATA", lib)
    print(f"{len(naks)} nakshatras, {len(lib)} library sections")


def write(name, var, obj):
    js = f"/* Generated by tools/gen_astro_data.py from the app's Astrology Library. */\nwindow.{var} = " + \
        json.dumps(obj, ensure_ascii=False, separators=(",", ":")) + ";\n"
    with open(os.path.join(HERE, "assets", "js", name), "w", encoding="utf-8", newline="\n") as f:
        f.write(js)


if __name__ == "__main__":
    main()
